# Generated by Django 6.0 on 2025-12-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hobby',
            field=models.CharField(max_length=100),
        ),
    ]
